{"tag": "function", "depth": 1, "time": 1711504267.5437434, "data": {"name": "connect_device", "call_args": {"uri": "Android:///127.0.0.1:16448"}, "start_time": 1711504267.3882337, "traceback": "Traceback (most recent call last):\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest\\utils\\logwraper.py\", line 131, in wrapper\n    res = f(*args, **kwargs)\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest\\core\\api.py\", line 74, in connect_device\n    dev = init_device(platform, uuid, **params)\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest\\core\\api.py\", line 42, in init_device\n    dev = cls(uuid, **kwargs)\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest\\core\\android\\android.py\", line 57, in __init__\n    self.adb = ADB(self.serialno, adb_path=adb_path, server_addr=host, display_id=self.display_id, input_event=self.input_event)\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 44, in __init__\n    self.connect()\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 282, in connect\n    if self.serialno and \":\" in self.serialno and (force or self.get_status() != \"device\"):\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 319, in get_status\n    raise AdbError(stdout, stderr)\nairtest.core.error.AdbError: stdout[] stderr[error: device offline\r\n]\n", "end_time": 1711504267.5437434}}
